dailyfresh/dailyfresh/urls.py
# coding=utf-8
"""dailyfresh URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin


from django.views.static import serve  # 上传文件处理函数
from .settings import MEDIA_ROOT

urlpatterns = [
    # 此处不能提前配置,如果df_goods下没有urls.py的话
    url(r'^admin/', include(admin.site.urls)),

    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),

    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置confur1
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}), # 此处serve MEDIA_ROOT为了能够浏览器访问到上传的图片

    url(r'^search/', include('haystack.urls')),
]

dailyfresh/df_cart/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

app_name = 'df_cart'

urlpatterns = [
    url(r'^$', views.cart, name="cart"),
    url(r'^add(\d+)_(\d+)/$', views.add, name="add"),
    url(r'^edit(\d+)_(\d+)/$', views.edit, name="edit"),
    url(r'^delete(\d+)/$', views.delete, name="delete"),
]

dailyfresh/df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^register_handle/?$', views.register_handle, name="register_handle"),
    url(r'^login/$', views.login, name="login"),
    url(r'^login_handle/$', views.login_handle, name="login_handle"),

    url(r'^register_exist/$', views.register_exist, name="register_exist"),

    url(r'^info/$', views.info, name="info"),
    url(r'^order/(\d+)/$', views.order, name="order"),
    url(r'^site/$', views.site, name="site"),

    url(r'^logout/$', views.logout, name="logout"),

]

dailyfresh/df_user/models.py
from django.db import models

# Create your models here.


class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ushou = models.CharField(max_length=20, default='')
    uaddress = models.CharField(max_length=100, default='')
    uyoubian = models.CharField(max_length=6, default='')
    uphone = models.CharField(max_length=11, default='')

dailyfresh/df_user/views.py
# coding=utf-8
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse

from hashlib import sha1

from django.http import JsonResponse
from . import user_decorator
from django.core.paginator import Paginator

from models import *
from df_order.models import *

# Create your views here.


def index(request):
    return HttpResponse('<h1>Index page of User</h1>')


def register(request):

    # 此数值传过去,会放在标签页的位置上
    context = {
        'title': '用户注册YL'
    }
    return render(request, 'df_user/register.html', context)


def register_handle(request):
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2= post.get('cpwd')
    uemail = post.get('email')
    # 判断两次密码一致性
    if upwd!=upwd2:
        return redirect('/user/register/')

    # 密码加密
    s1 = sha1()
    s1.update(upwd)
    upwd3 = s1.hexdigest()

    # 创建对象
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    user.save()
    # 注册成功，转到登陆界面
    return redirect('/user/login/')


def login(request):

    uname = request.COOKIES.get('uname', '')
    context = {
        'title': '用户登陆',
        'error_name': 0,
        'error_pwd': 0,
        'uname': uname,
    }
    return render(request, 'df_user/login.html', context)


def login_handle(request):
    # 接收请求信息
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu=post.get('jizhu', 0)

    # 根据用户名查询对象
    users = UserInfo.objects.filter(uname=uname)

    # 判断用户密码并跳转
    if len(users) != 0:
        # user name founded 111
        s1 = sha1()
        s1.update(upwd)

        if s1.hexdigest() == users[0].upwd:
            # password right 222
            # todo redirect to /user/info/
            # 此处的url是user_decorator.py中预先存入的，便于返回之前未登陆的页面。如果没有就使用/
            url = request.COOKIES.get('url', '/')
            red = HttpResponseRedirect(url)
            # whether checked remember user name 333
            if jizhu != 0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)  # cookie 立刻过期

            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red

        else:
            # password false 222
            context = {
                'title': '用户名登陆',
                'error_name': 0,
                'error_pwd': 1,
                'uname': uname,
                'upwd': upwd,
            }
            return render(request, 'df_user/login.html', context)

    else:
        # user name not exist 111
        context = {
            'title': '用户名登陆',
            'error_name': 1,
            'error_pwd': 0,
            'uname': uname,
            'upwd': upwd,
        }
        return render(request, 'df_user/login.html', context)


def logout(request):
    request.session.flush()
    return redirect('/')


def register_exist(request):
    uname = request.GET.get('uname')

    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count': count})
    # two line for test
    # context = {'count': count}
    # return render(request, 'df_user/debug.html', context)


@user_decorator.login
def info(request):  # 用户中心

    user_email = UserInfo.objects.get(id=request.session.get('user_id')).uemail

    # 最近浏览
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_ids1 = goods_ids.split(',')
    goods_list = []

    if goods_ids1:
        for goods_id in goods_ids1:
            # 如果goods_ids1为空时，下一行有bug。todo
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
            explain = '最近浏览'
    else:
        explain = '无最近浏览'

    context = {
        'title': '用户中心',
        'user_email': user_email,
        'user_name': request.session.get('user_name'),
        'page_name': 1,
        'goods_list': goods_list,
        'explain': explain,
    }

    return render(request, 'df_user/user_center_info.html', context)


@user_decorator.login
def order(request, index):
    user_id = request.session['user_id']
    orders_list = OrderInfo.objects.filter(ouser_id=int(user_id)).order_by('-odate')
    paginator = Paginator(orders_list, 2)
    page = paginator.page(int(index))
    context = {
        'paginator': paginator,
        'page': page,
        'orders_list': orders_list,
        'title': "用户中心",
        'page_name': 1,
    }

    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == 'POST':
        post=request.POST
        user.ushou=post.get('ushou')
        user.uaddress=post.get('uaddress')
        user.uyoubian=post.get('uyoubian')
        user.uphone=post.get('uphone')
        user.save()

    context = {'title': "用户中心", 'user': user}
    return render(request, 'df_user/user_center_site.html', context)

dailyfresh/templates/df_user/debug.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{count}}

</body>
</html>

dailyfresh/templates/df_user/login.html
{% extends 'base_foot.html' %}

{% block head %}

<script>

$(function(){

    name_error = false;
    pwd_error = false;

    if({{ error_name }}==1){
        $('.user_error').html('用户名错误').show();
    }
    if({{ error_pwd }}==1){
        $('.pwd_error').html('密码错误').show();
    }
    $('.name_input').blur(function(){
        if($('.name_input').val().length=0){
            $('.user_error').html('请填写用户名').show();
            name_error = false;
        }else{
            $('.user_error').hide();
            name_error = true;
        }
    });

    $('.pass_input').blur(function(){
        if($('.pass_input').val().length=0){
            $('.pwd_error').html('请输入密码').show();
            pwd_error = false;
        }else{
            $('.pwd_error').hide();
            pwd_error =true;
        }
    });

})

</script>

{% endblock head %}

{% block body%}

	<div class="login_top clearfix">
		<!--todo-->
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url "df_user:register" %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	

{% endblock body %}


dailyfresh/templates/df_user/register.html
{% extends 'base_foot.html' %}

{% block head %}
<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock head %}


{% block body %}

	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url "df_user:login" %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<!--id=reg_form is need for register.js to work-->
				<form action="/user/register_handle/" id="reg_form" method="post">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<!--todo Button press visual effect-->
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>


	


{% endblock body %}


dailyfresh/templates/df_user/user_center_info.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url "df_user:info" %}" class="active">· 个人信息</a></li>
				<li><a href="/user/order/1">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
			<div class="info_con clearfix">
			<h3 class="common_title2">基本信息</h3>
					<ul class="user_info_list">
						<li><span>用户名：</span>{{ user_name }}</li>
						<li><span>联系方式：</span>{{ user_phone }}</li>
						<li><span>联系地址：</span>{{ user_address }}</li>
					</ul>
			</div>
            <h3 class="common_title2">{{ explain }}666</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {%  for good in goods_list %}
                    <li>
                        <a href="/{{ good.id }}/"><img src="/media/{{ good.gpic }}"></a>
                        <h4><a href="/{{ good.id }}/">{{ good.gtitle }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ good.gprice }}</span>
                            <span class="unit">{{ good.gprice }}/{{ good.gunit }}</span>
                            <a href="/cart/add{{ good.id }}_1/" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                    {% endfor %}
				</ul>
            </div>
		</div>
	</div>
{% endblock center_body %}




dailyfresh/templates/df_user/user_center_order.html
{% extends 'base.html' %}

{% block center_body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
				<li><a href="{% url "df_user:order" 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>



				<div class="pagenation">
                    {% if page.has_previous %}
					    <a href="{% url "df_user:order" page.previous_page_number %}">上一页</a>
                    {% endif %}

                    {% for index in paginator.page_range %}
                        {% if index == page.number %}
                            <a href="{% url "df_user:order" index %}" class="active">{{ index }}</a>
                        {% else %}
                            <a href="{% url "df_user:order" index %}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if page.has_next %}
					    <a href="{% url "df_user:order" page.next_page_number %}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>

    <script type="text/javascript">
    $(function () {
        $('.col04').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().find('.good_price').text();
            $(this).html(parseFloat(count,2)*parseFloat(price,2)+'元');
            }

        )
        }
    )

    </script>

{% endblock center_body %}

dailyfresh/templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
				<li><a href="{% url "df_user:order" 1 %}">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
                        <dt>收件人：{{ user.ushou }}</dt>
                        <dt>电话：{{ user.uphone }}</dt>
                        <dt>当前地址：{{ user.uaddress }}</dt>
{#                        <a href="/user/place_order" style="display: block; width: 80px; height:30px; line-height: 30px; text-align: center;font-size: 13px; " class="info_submit">提交订单</a>#}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url "df_user:site" %}" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{ user.ushou }}">
						</div>
                        <div class="form_group">
                            <label>手机：</label>
                            <input type="text" name="uphone" value="{{ user.uphone }}">
                        </div>
                        <div class="form_group">
                            <label>邮编：</label>
                            <input type="text" name="uyoubian" value="{{ user.uyoubian }}">
                        </div>
                        <div class="form_group form_group2">
                            <label>详细地址：</label>
                            <textarea class="site_area" name="uaddress" >{{ user.uaddress }}</textarea>
                        </div>
						<input type="submit" name="" value="修改地址" class="info_submit">
					</form>
				</div>
		</div>
	</div>



{% endblock center_body %}